apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: chpassword
spec:
  storageClassName: csi-cephfs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
